disabled_rules:
- trailing_whitespace
- multiple_closures_with_trailing_closure
- weak_delegate
- large_tuple
- for_where
- implicit_getter
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- Stream
line_length:
    warning: 350
    error: 450
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1500
    error: 2000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
    
identifier_name:
    min_length: 0
    allowed_symbols: ["_"]

cyclomatic_complexity: 30
    
reporter: "xcode"